<a href="https://colab.research.google.com/github/ghatagessg/ghatagessg/blob/main/2Dmatrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 2D matrix operations
import numpy as np

# create A and B matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9],[11, 12, 13]])

print ("\nA: ")
print (A)
print ("\nB: ")
print (B)

# Element wise addition
C=A+B
print ("\nA + B :")
print (C)

# Element wise subtraction
C=A-B
print ("\nA - B :")
print (C)

# Element wise multiplication
C=A*B
print ("\nA * B :")
print (C)





A: 
[[1 2 3]
 [4 5 6]]

B: 
[[ 7  8  9]
 [11 12 13]]

A + B :
[[ 8 10 12]
 [15 17 19]]

A - B :
[[-6 -6 -6]
 [-7 -7 -7]]

A * B :
[[ 7 16 27]
 [44 60 78]]
